id: A4C88F8D8
title: 'Vajra Net: The Ancillary Preliminary and Concluding Practices for the Three
  Drops, the Guru Yogas for Venerable Marpa, Mila, and Gampopa'
type: translation
pechas:
- I4F72C940
- IF00D0470
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 12:45:15.449868
  last_modified_at: 2023-01-04 12:45:15.449891
  collections:
  - Jokyab Pema Trinlé Nyingpo
  - Works of Tibetan Masters
alignment_to_base:
  I4F72C940/A6DA: 6B17
  IF00D0470/D334: 6B17
